global using AutoMapper;
global using Bookify.web.Core.Consts;
global using Bookify.web.Core.Models;
global using Bookify.web.Core.ViewModel;
global using Bookify.web.Data;
global using Bookify.web.Filters;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
